spring:
    application:
        name: timetables
    datasource:
        url: jdbc:postgresql://localhost:5432/timetables
        username: heiner
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: validate
        show-sql: true
        open-in-view: false
    flyway:
        enabled: true
    codec:
        max-in-memory-size: 500KB

# DB Station&Service AG
bahn:
    api:
        client-id: ${BAHN_CLIENT_ID}
        key: ${BAHN_CLIENT_SECRET}

# Optional: Logging-Konfiguration
logging:
    level:
        "[org.springframework]": INFO
        "[org.hibernate]": INFO
        "[eu.bilch.timetables]": DEBUG
        "[org.flywaydb]": INFO
